openapi: 3.0.1
info:
  title: Escore API Docs
  description: API for support mobile app environtment and machine learning model.
  version: 1.0.0
servers:
  - url: https://escore-app.et.r.appspot.com
    description: Production server
  - url: http://localhost:8000
    description: Local server
paths:
  /api/register:
    post:
      summary: User register
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  example: Abdul Rojak
                email:
                  type: string
                  example: abdul123@gmail.com
                password:
                  type: string
                  example: abdulgntg
      responses:
        '201':
          description: User registered successfully!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: User registered successfully!
        '400':
          description: Email already registered!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Username already exists!
        '500':
          description: Internal server error!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Internal server error!

  /api/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: abdul@gmail.com
                password:
                  type: string
                  example: abdulgntg
      responses:
        '200':
          description: Login successful!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: succes
                  message:
                    type: string
                    example: Login successful!
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        '401':
          description: Emmail and password do not match!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Email and password do not match!
        '500':
          description: Internal server error!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Internal server error!

# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
