openapi: 3.0.1
info:
  title: Escore API Docs
  description: API for support mobile app environtment and machine learning model.
  version: 1.0.0
servers:
  - url: https://escore-app.et.r.appspot.com
    description: Production server
  - url: http://localhost:8000
    description: Local server
paths:
  /api/register:
    post:
      summary: For user register
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  example: Abdul Rojak
                email:
                  type: string
                  example: abdul123@gmail.com
                password:
                  type: string
                  example: abdulgntg
      responses:
        '201':
          description: User registered successfully!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
        '500':
          description: Internal server error!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string


  /api/login:
    post:
      summary: For user login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: abdul@gmail.com
                password:
                  type: string
                  example: abdulgntg
      responses:
        '200':
          description: Success logged in!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
                  loginResult:
                    type: object
                    properties:
                      userId:
                        type: string
                      email:
                        type: string
                      fullName:
                        type: string
                      token:
                        type: string
        '500':
          description: Internal server error!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string


  /api/history/{email}:
    get:
      summary: For history predictions
      tags:
        - Model Prediction
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
            format: email
      responses:
        '200':
          description: History predictions retrieved successfully!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
                  email:
                    type: string
                  predictions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        essay:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                        predicted_result:
                          type: object
                          properties:
                            score:
                              type: string
                            suggestion:
                              type: string
        '500':
          description: Internal server error!
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string


# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
